### Kullnıcıları listeleme
GET http://localhost:8080/users/
Accept: application/json

### Kullanıcı kaydetme
POST http://localhost:8080/users/
Content-Type: application/json

{
  "name": "mehmet",
  "surname": "dikkulah",
  "email": "mehmet@gmail.com",
  "password": "123456",
  "customerList": []
}

### Maile göre User listeleme
GET http://localhost:8080/users/mehmet@gmail.com
Accept: application/json

### Maile göre Userın Customerlearını listeleme
GET http://localhost:8080/users/mehmet@gmail.com/customers
Accept: application/json


